services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - nodejs-app-frontend-network
    ports:
      - "${EXPOSE_APP_PORT}:4200"
    volumes:
      - ./frontend:/app
      - nodejs-app-frontend-node-modules:/app/node_modules
    tty: true
    command: sh -c "ng serve --host=0.0.0.0"

networks:
  nodejs-app-frontend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.5.0/24

volumes:
  nodejs-app-frontend-node-modules:
