services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "${EXPOSE_APP_PORT}:4200"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    tty: true
    command: sh -c "ng serve --host=0.0.0.0"

volumes:
  frontend_node_modules:
